### ISSUE TITLE
Error building project after upgrade to Flutter 1.17

### ISSUE THREAD

**Issue by javierhinmel** [OpenFlutter/neeko#13]
A recent update ([https://github.com/flutter/flutter/pull/51435]) has removed the isInitialRoute parameter from RouteSettings.

Error dump:

Compiler message:
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/neeko-0.0.7/lib/src/neeko_player_widget.dart:196:46: Error: No named parameter with the name 'isInitialRoute'.
      settings: RouteSettings(name: "neeko", isInitialRoute: false),
                                             ^^^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/widgets/navigator.dart:458:9: Context: Found this candidate, but the arguments don't match.
  const RouteSettings({
        ^^^^^^^^^^^^^

Compiler message:
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/neeko-0.0.7/lib/src/neeko_player_widget.dart:196:46: Error: No named parameter with the name 'isInitialRoute'.
      settings: RouteSettings(name: "neeko", isInitialRoute: false),
                                             ^^^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/widgets/navigator.dart:458:9: Context: Found this candidate, but the arguments don't match.
  const RouteSettings({
        ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

![image](https://user-images.githubusercontent.com/60926533/81355065-a0333180-90a3-11ea-985d-fe3fb78579aa.png)

**Comment by JarvanMo** [comment]
OK, thanks for your report, I'll have a update later.

**Comment by JarvanMo** [comment]
Hi, please try the new version.

**Comment by javierhinmel** [comment]
@JarvanMo you rock!. 
It's works. 
Thank you!
