### ISSUE TITLE
local video gives exception

### ISSUE THREAD

**Issue by aifrosals** [OpenFlutter/neeko#15]
When I use 
    ```
     (DataSource.asset(
            "pushup1.mp4",
              displayName: "displayName"));
```
it gave the following exception

`E/ExoPlayerImplInternal(  764): Source error.
E/ExoPlayerImplInternal(  764): com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: pushup1.mp4: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(  764): 	at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
E/ExoPlayerImplInternal(  764): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
E/ExoPlayerImplInternal(  764): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(  764): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(  764): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(  764): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/ExoPlayerImplInternal(  764): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/ExoPlayerImplInternal(  764): 	at java.lang.Thread.run(Thread.java:818)
E/ExoPlayerImplInternal(  764): Caused by: java.io.FileNotFoundException: pushup1.mp4: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(  764): 	at libcore.io.IoBridge.open(IoBridge.java:487)
E/ExoPlayerImplInternal(  764): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
E/ExoPlayerImplInternal(  764): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
E/ExoPlayerImplInternal(  764): 	at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65)
E/ExoPlayerImplInternal(  764): 	... 7 more
E/ExoPlayerImplInternal(  764): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(  764): 	at libcore.io.Posix.open(Native Method)
E/ExoPlayerImplInternal(  764): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
E/ExoPlayerImplInternal(  764): 	at libcore.io.IoBridge.open(IoBridge.java:473)
E/ExoPlayerImplInternal(  764): 	... 10 more
E/flutter (  764): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: pushup1.mp4: open failed: ENOENT (No such file or directory), null)
E/flutter (  764): 
`

flutter version is Flutter 1.17.1 stable

**Comment by JarvanMo** [comment]
Is your path correct? neeko just calls video_player while playing

**Comment by aifrosals** [comment]
Yes, let me inform you that there the path I used was assets/pushup1.mp4, I will edit that in my question but it gave the same exception. assets/pushup1.mp4 ENOENT,  while I used the same path in the video player and it did work

**Comment by JarvanMo** [comment]
I think I got the bug and will fix within one day. Thanks for your report.
