### ISSUE TITLE
Player doesn't support all online video streaming links

### ISSUE THREAD

**Issue by Hassico** [OpenFlutter/neeko#3]
I am streaming some anime content on this player(it is nice by the way), but the player cannot recognize the links in some cases and is unable to play the video. Also when pressing the back button from the fullscreen mode, it would be better if it returns the portrait mode. The player does not show you a circular progress indicator when loading or buffering the video. Finally, is it possible that the loaded video parts stays in memory temporary, only while watching, so that when scrolling the video it does not load all over again. Thank you for this wonderful plugin. Keep going.

**Comment by JarvanMo** [comment]
Thanks for reporting and this package is still under development.
If you have streaming problems, I think that's `video_player`'s reason. `Neeko` does nothing about streaming. As far as I know, `video_player` is based on `ExoPlayer` on native Android, so if you want play streams like `rtsp`, you have to re-write `video_player`. Take a look at [ExoPlayer](https://github.com/google/ExoPlayer) for detail. By the way , could you tell me what of stream you tested?
Pressing back button from fullscreen mode will be back to portrait mode in current version. But please notice that you have to trigger fullscreeen mode by the enter-fullscreen button. If not so, there'll be a little work to do. Maybe I remember it wrong.  I'll test it later. So it's necessary to tell me how to reproduce.
I'll check the circular progress indicator as soon as possible.
At last, `Neeko` is just a widget based on `video_player` now. I think memory temporary should be `video_player`'s feature.Besides, I don't know how to load it in memory using `video_player`, haha.
If anyone knows how to do that, just tell me.
