### ISSUE TITLE
if video not initialize ready to play will have more video controller play much more when we click 

### ISSUE THREAD

**Issue by peterkuch** [OpenFlutter/neeko#7]
if video first time not initialize ready to play video play will
- count by click other video
- crash video player 
- can not stop it unless app kill.

by solution i have to share with you with neeko Player 
- Listener video completed initialize make sure the first video done for Video Player can play it.
- Prevent user click other video before success initialize by show loading dialog on screen.
- sometime core lib neeko not sure video completed to play because sometime i guest that video show play controller allow user click to play but video not completed init yet. avoid like that please delayed hide loading view for user when notify loadVideoSuccess().
`
NeekoPlayerWidget player;
VideoControllerWrapper videoControllerWrapper;

//Listener func callback
VoidCallback loadVideoSuccess() {
    //Delay
    Future.delayed(const Duration(milliseconds: 4000), () {
      //hide your dialog progress.
    });
  }
if (videoControllerWrapper == null) {
      videoControllerWrapper = VideoControllerWrapper(DataSource.network(
          widget.lessonFromList.videoTutorial.toString(),
          displayName: widget.lessonFromList.name));
      videoControllerWrapper.addListener(loadVideoSuccess);
    }
@override
 void initState() {
    if (videoControllerWrapper == null) {
      videoControllerWrapper = VideoControllerWrapper(DataSource.network(
          widget.lessonFromList.videoTutorial.toString(),
          displayName: widget.lessonFromList.name));
      videoControllerWrapper.addListener(loadVideoSuccess);
    }
}

@override
  Widget build(BuildContext context) {
    player = NeekoPlayerWidget(
        playerOptions:
          NeekoPlayerOptions(preferredOrientationsWhenExitLandscape: [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown,
        ], useController: true),
        onPortraitBackTap: () {},
        videoControllerWrapper: videoControllerWrapper,
        );
   return Container(
            color: AppColor.appBgColor,
            child: player);
}
`

**Comment by JarvanMo** [comment]
Thanks for reporting. I'm busy doing work these days. I'll try my to best to make this better. Currently neeko doesn't handle audio focus change events on Android, so it's common that neeko is still playing while other video or audio are active.

**Comment by JarvanMo** [comment]
BTW, what's neekKo? Can you share the link? Thank you.

**Comment by peterkuch** [comment]
> BTW, what's neekKo? Can you share the link? Thank you.

I am so sorry, i wrote wrong name,  it is neeko. i found your lib this nice too, not much more crash when i use video_play not easy control video list but your Lib can control if i try to delay  before video init completed to play.
